sudo: required

language: c

jobs:
  fast_finish: true
  include:
  - os: linux
    env: OCAML_VERSION=4.05
  - os: linux
    env: OCAML_VERSION=4.06
  - os: linux
    env: OCAML_VERSION=4.07
  - os: linux
    env: OCAML_VERSION=4.08
  - os: linux
    env: OCAML_VERSION=4.09
  - os: osx
    env: OCAML_VERSION=4.09

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install protobuf ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq protobuf-compiler ; fi

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh ;
    bash -ex .travis-ocaml.sh ;

script:
  - set -ex ;
    export OPAMYES=1 ;
    export DEPS='benchmark camlp5 cppo dune.1.11.4 markup num ocaml ounit ocurl piqi piqilib redis redis-sync stdlib-shims unidecode.0.2.0 uucp uutf yojson zarith' ;
    eval $(opam config env) ;
    opam pin list ;
    opam pin remove markup --no-action ;
    opam pin remove piqilib --no-action ;
    opam pin remove piqi --no-action ;
    opam update ;
    opam install depext ;
    opam depext $DEPS ;
    opam install $DEPS ;
    make ci ;
