sudo: required

language: c

jobs:
  fast_finish: true
  include:
  - os: linux
    env: OCAML_VERSION=4.05
  - os: linux
    env: OCAML_VERSION=4.06
  - os: linux
    env: OCAML_VERSION=4.07
  - os: linux
    env: OCAML_VERSION=4.08
  - os: linux
    env: OCAML_VERSION=4.09
  - os: linux
    env: OCAML_VERSION=4.10
  - os: freebsd
    env: OCAML_VERSION=4.09
  allowed_failures:
  - os: linux
    env: OCAML_VERSION=4.10

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then command -v protoc >/dev/null 2>&1 || sudo apt-get install -qq protobuf-compiler ; fi
  - if [[ "$TRAVIS_OS_NAME" == "freebsd" ]]; then command -v protoc >/dev/null 2>&1 || sudo pkg install -qy protobuf ; fi

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh ;
    bash -ex .travis-ocaml.sh ;

script:
  - set -ex ;
    export OPAMYES=1 ;
    export DEPS='benchmark calendars camlp5.7.12 cppo dune.1.11.4 jingoo markup num ocaml ounit ocurl piqi piqilib redis redis-sync stdlib-shims unidecode.0.2.0 uucp uunf uutf yojson zarith' ;
    eval $(opam config env) ;
    opam update ;
    opam install depext ;
    opam depext $DEPS ;
    opam install $DEPS ;
    if [[ "$TRAVIS_OS_NAME" == "freebsd" ]]; then gmake ci ; else make ci ; fi ;
