sudo: required

language: c

os:
  - linux
  - osx

env:
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.opam/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install protobuf ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq protobuf-compiler ; fi

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh ;
    bash -ex .travis-ocaml.sh ;

script:
  - set -ex ;
    export OPAMYES=1 ;
    export DEPS='benchmark camlp5 cppo dune markup ocaml ounit num ocurl piqi piqilib redis redis-sync stdlib-shims yojson zarith' ;
    eval $(opam config env) ;
    opam pin list ;
    opam pin remove markup --no-action ;
    opam pin remove piqilib --no-action ;
    opam pin remove piqi --no-action ;
    opam update ;
    opam install depext ;
    opam depext $DEPS ;
    opam install $DEPS ;
    make ci ;
